-- OmniShare cloud backend
-- Apply to the Supabase project used by OmniShare.

create table if not exists public.omnishare_files (
  id uuid primary key default gen_random_uuid(),
  share_id text not null unique,
  owner_id uuid not null references auth.users(id) on delete cascade,
  storage_path text not null unique,
  original_name text not null,
  size_bytes bigint not null check (size_bytes >= 0 and size_bytes <= 104857600),
  mime_type text not null default 'application/octet-stream',
  note text,
  created_at timestamptz not null default now(),
  expires_at timestamptz,
  download_count bigint not null default 0 check (download_count >= 0),
  last_downloaded_at timestamptz
);

create index if not exists omnishare_files_owner_idx on public.omnishare_files(owner_id);
create index if not exists omnishare_files_share_idx on public.omnishare_files(share_id);
create index if not exists omnishare_files_expires_idx on public.omnishare_files(expires_at);

alter table public.omnishare_files enable row level security;

drop policy if exists "omnishare owner can read files" on public.omnishare_files;
create policy "omnishare owner can read files"
on public.omnishare_files for select
to authenticated
using ((select auth.uid()) = owner_id);

drop policy if exists "omnishare owner can insert files" on public.omnishare_files;
create policy "omnishare owner can insert files"
on public.omnishare_files for insert
to authenticated
with check ((select auth.uid()) = owner_id);

drop policy if exists "omnishare owner can update files" on public.omnishare_files;
create policy "omnishare owner can update files"
on public.omnishare_files for update
to authenticated
using ((select auth.uid()) = owner_id)
with check ((select auth.uid()) = owner_id);

drop policy if exists "omnishare owner can delete files" on public.omnishare_files;
create policy "omnishare owner can delete files"
on public.omnishare_files for delete
to authenticated
using ((select auth.uid()) = owner_id);

revoke all on table public.omnishare_files from anon;
grant select, insert, update, delete on table public.omnishare_files to authenticated;

create table if not exists public.omnishare_activity (
  id bigint generated by default as identity primary key,
  owner_id uuid not null references auth.users(id) on delete cascade,
  file_id uuid references public.omnishare_files(id) on delete set null,
  event_type text not null check (event_type in ('upload','download','share','delete')),
  share_id text not null,
  file_name text not null,
  detail jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create index if not exists omnishare_activity_owner_idx on public.omnishare_activity(owner_id);
create index if not exists omnishare_activity_created_idx on public.omnishare_activity(created_at desc);

alter table public.omnishare_activity enable row level security;

drop policy if exists "omnishare owner can read activity" on public.omnishare_activity;
create policy "omnishare owner can read activity"
on public.omnishare_activity for select
to authenticated
using ((select auth.uid()) = owner_id);

drop policy if exists "omnishare owner can insert activity" on public.omnishare_activity;
create policy "omnishare owner can insert activity"
on public.omnishare_activity for insert
to authenticated
with check ((select auth.uid()) = owner_id);

drop policy if exists "omnishare owner can delete activity" on public.omnishare_activity;
create policy "omnishare owner can delete activity"
on public.omnishare_activity for delete
to authenticated
using ((select auth.uid()) = owner_id);

revoke all on table public.omnishare_activity from anon;
grant select, insert, delete on table public.omnishare_activity to authenticated;
grant usage, select on sequence public.omnishare_activity_id_seq to authenticated;

insert into storage.buckets (id, name, public, file_size_limit)
values ('omnishare-files', 'omnishare-files', false, 104857600)
on conflict (id) do update
set public = false,
    file_size_limit = 104857600;

drop policy if exists "omnishare authenticated upload own path" on storage.objects;
create policy "omnishare authenticated upload own path"
on storage.objects for insert
to authenticated
with check (
  bucket_id = 'omnishare-files'
  and (storage.foldername(name))[1] = (select auth.uid())::text
);

drop policy if exists "omnishare owner read own objects" on storage.objects;
create policy "omnishare owner read own objects"
on storage.objects for select
to authenticated
using (
  bucket_id = 'omnishare-files'
  and (storage.foldername(name))[1] = (select auth.uid())::text
);

drop policy if exists "omnishare owner delete own objects" on storage.objects;
create policy "omnishare owner delete own objects"
on storage.objects for delete
to authenticated
using (
  bucket_id = 'omnishare-files'
  and (storage.foldername(name))[1] = (select auth.uid())::text
);
